Level_5_EventObjects::
	object_event 1, EVENT_OBJ_GFX_ITEM_BALL, 0, 9, 5, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, FALSE, 0, Level_5_Ball_1, FLAG_0x4A9
	object_event 2, EVENT_OBJ_GFX_ITEM_BALL, 0, 6, 13, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, FALSE, 0, Level_5_Ball_2, FLAG_0x4AA
	object_event 3, EVENT_OBJ_GFX_AQUA_MEMBER_F, 0, 13, 14, 3, MOVEMENT_TYPE_FACE_DOWN_AND_RIGHT, 0, 0, TRUE, 3, Level_5_Trainer_1, FLAG_0x4AB
	object_event 4, EVENT_OBJ_GFX_KIRLIA, 0, 13, 6, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, FALSE, 0, Level_5_Warp, 0

Level_5_MapEvents::
	map_events Level_5_EventObjects, 0x0, 0x0, 0x0
