Level_7_EventObjects::
	object_event 1, EVENT_OBJ_GFX_ITEM_BALL, 0, 21, 7, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, FALSE, 0, Level_7_Ball_1, FLAG_L7_BALL_1
	object_event 2, EVENT_OBJ_GFX_ITEM_BALL, 0, 12, 18, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, FALSE, 0, Level_7_Ball_2, FLAG_L7_BALL_2
	object_event 3, EVENT_OBJ_GFX_HIKER, 0, 17, 12, 3, MOVEMENT_TYPE_WANDER_AROUND, 3, 3, TRUE, 3, Level_7_Trainer_1, FLAG_L7_TRAINER_1
	object_event 4, EVENT_OBJ_GFX_KIRLIA, 0, 11, 6, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, FALSE, 0, Level_7_Warp, 0

Level_7_MapEvents::
	map_events Level_7_EventObjects, 0x0, 0x0, 0x0
