Level_2_EventObjects::
	object_event 1, EVENT_OBJ_GFX_KIRLIA, 0, 2, 4, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, FALSE, 0, Level_2_Warp, 0
	object_event 2, EVENT_OBJ_GFX_PSYCHIC_M, 0, 6, 11, 3, MOVEMENT_TYPE_FACE_UP, 0, 0, TRUE, 1, Level_2_Trainer_1, FLAG_L2_TRAINER_1
	object_event 3, EVENT_OBJ_GFX_HEX_MANIAC, 0, 10, 4, 3, MOVEMENT_TYPE_FACE_DOWN_LEFT_AND_RIGHT, 0, 0, TRUE, 3, Level_2_Trainer_2, FLAG_L2_TRAINER_2
	object_event 4, EVENT_OBJ_GFX_ITEM_BALL, 0, 8, 2, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, FALSE, 0, Level_2_Ball_1, FLAG_L2_BALL_1
	object_event 5, EVENT_OBJ_GFX_ITEM_BALL, 0, 1, 11, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, FALSE, 0, Level_2_Ball_2, FLAG_L2_BALL_2

Level_2_MapEvents::
	map_events Level_2_EventObjects, 0x0, 0x0, 0x0
