from enum import IntEnum
import random

global POCKET_WEIGHT, TOTAL_WEIGHT, ALL_ITEMS

class Pocket(IntEnum):
    """Enumeration for the different object types."""
    POCKET_POKE_BALLS = 0
    POCKET_ITEMS = 1
    POCKET_BERRIES = 2
    POCKET_KEY_ITEMS = 3
    POCKET_TM_HM = 4

POCKET_WEIGHT = [0 for i in range(5)]
TOTAL_WEIGHT = -1

# [Name, ID, Pocket, Weight]
ALL_ITEMS = [
    ["MASTER BALL",
        "ITEM_MASTER_BALL",
        Pocket.POCKET_POKE_BALLS,
        1],
    ["ULTRA BALL",
        "ITEM_ULTRA_BALL",
        Pocket.POCKET_POKE_BALLS,
        2],
    ["GREAT BALL",
        "ITEM_GREAT_BALL",
        Pocket.POCKET_POKE_BALLS,
        5],
    ["POKé BALL",
        "ITEM_POKE_BALL",
        Pocket.POCKET_POKE_BALLS,
        10],
    ["SAFARI BALL",
        "ITEM_SAFARI_BALL",
        Pocket.POCKET_POKE_BALLS,
        2],
    ["NET BALL",
        "ITEM_NET_BALL",
        Pocket.POCKET_POKE_BALLS,
        3],
    ["DIVE BALL",
        "ITEM_DIVE_BALL",
        Pocket.POCKET_POKE_BALLS,
        3],
    ["NEST BALL",
        "ITEM_NEST_BALL",
        Pocket.POCKET_POKE_BALLS,
        3],
    ["REPEAT BALL",
        "ITEM_REPEAT_BALL",
        Pocket.POCKET_POKE_BALLS,
        1],
    ["TIMER BALL",
        "ITEM_TIMER_BALL",
        Pocket.POCKET_POKE_BALLS,
        2],
    ["LUXURY BALL",
        "ITEM_LUXURY_BALL",
        Pocket.POCKET_POKE_BALLS,
        1],
    ["PREMIER BALL",
        "ITEM_PREMIER_BALL",
        Pocket.POCKET_POKE_BALLS,
        1],
    ["POTION",
        "ITEM_POTION",
        Pocket.POCKET_ITEMS,
        10],
    ["ANTIDOTE",
        "ITEM_ANTIDOTE",
        Pocket.POCKET_ITEMS,
        3],
    ["BURN HEAL",
        "ITEM_BURN_HEAL",
        Pocket.POCKET_ITEMS,
        3],
    ["ICE HEAL",
        "ITEM_ICE_HEAL",
        Pocket.POCKET_ITEMS,
        3],
    ["AWAKENING",
        "ITEM_AWAKENING",
        Pocket.POCKET_ITEMS,
        3],
    ["PARLYZ HEAL",
        "ITEM_PARALYZE_HEAL",
        Pocket.POCKET_ITEMS,
        3],
    ["FULL RESTORE",
        "ITEM_FULL_RESTORE",
        Pocket.POCKET_ITEMS,
        1],
    ["MAX POTION",
        "ITEM_MAX_POTION",
        Pocket.POCKET_ITEMS,
        1],
    ["HYPER POTION",
        "ITEM_HYPER_POTION",
        Pocket.POCKET_ITEMS,
        2],
    ["SUPER POTION",
        "ITEM_SUPER_POTION",
        Pocket.POCKET_ITEMS,
        5],
    ["FULL HEAL",
        "ITEM_FULL_HEAL",
        Pocket.POCKET_ITEMS,
        1],
    ["REVIVE",
        "ITEM_REVIVE",
        Pocket.POCKET_ITEMS,
        6],
    ["MAX REVIVE",
        "ITEM_MAX_REVIVE",
        Pocket.POCKET_ITEMS,
        2],
    ["FRESH WATER",
        "ITEM_FRESH_WATER",
        Pocket.POCKET_ITEMS,
        3],
    ["SODA POP",
        "ITEM_SODA_POP",
        Pocket.POCKET_ITEMS,
        3],
    ["LEMONADE",
        "ITEM_LEMONADE",
        Pocket.POCKET_ITEMS,
        3],
    ["MOOMOO MILK",
        "ITEM_MOOMOO_MILK",
        Pocket.POCKET_ITEMS,
        2],
    ["ENERGYPOWDER",
        "ITEM_ENERGY_POWDER",
        Pocket.POCKET_ITEMS,
        1],
    ["ENERGY ROOT",
        "ITEM_ENERGY_ROOT",
        Pocket.POCKET_ITEMS,
        1],
    ["HEAL POWDER",
        "ITEM_HEAL_POWDER",
        Pocket.POCKET_ITEMS,
        1],
    ["REVIVAL HERB",
        "ITEM_REVIVAL_HERB",
        Pocket.POCKET_ITEMS,
        1],
    ["ETHER",
        "ITEM_ETHER",
        Pocket.POCKET_ITEMS,
        6],
    ["MAX ETHER",
        "ITEM_MAX_ETHER",
        Pocket.POCKET_ITEMS,
        1],
    ["ELIXIR",
        "ITEM_ELIXIR",
        Pocket.POCKET_ITEMS,
        1],
    ["MAX ELIXIR",
        "ITEM_MAX_ELIXIR",
        Pocket.POCKET_ITEMS,
        1],
    ["LAVA COOKIE",
        "ITEM_LAVA_COOKIE",
        Pocket.POCKET_ITEMS,
        1],
    ["BLUE FLUTE",
        "ITEM_BLUE_FLUTE",
        Pocket.POCKET_ITEMS,
        1],
    ["YELLOW FLUTE",
        "ITEM_YELLOW_FLUTE",
        Pocket.POCKET_ITEMS,
        1],
    ["RED FLUTE",
        "ITEM_RED_FLUTE",
        Pocket.POCKET_ITEMS,
        1],
    ["BLACK FLUTE",
        "ITEM_BLACK_FLUTE",
        Pocket.POCKET_ITEMS,
        1],
    ["WHITE FLUTE",
        "ITEM_WHITE_FLUTE",
        Pocket.POCKET_ITEMS,
        1],
    ["BERRY JUICE",
        "ITEM_BERRY_JUICE",
        Pocket.POCKET_ITEMS,
        1],
    ["SACRED ASH",
        "ITEM_SACRED_ASH",
        Pocket.POCKET_ITEMS,
        1],
    ["SHOAL SALT",
        "ITEM_SHOAL_SALT",
        Pocket.POCKET_ITEMS,
        1],
    ["SHOAL SHELL",
        "ITEM_SHOAL_SHELL",
        Pocket.POCKET_ITEMS,
        1],
    ["RED SHARD",
        "ITEM_RED_SHARD",
        Pocket.POCKET_ITEMS,
        1],
    ["BLUE SHARD",
        "ITEM_BLUE_SHARD",
        Pocket.POCKET_ITEMS,
        1],
    ["YELLOW SHARD",
        "ITEM_YELLOW_SHARD",
        Pocket.POCKET_ITEMS,
        1],
    ["GREEN SHARD",
        "ITEM_GREEN_SHARD",
        Pocket.POCKET_ITEMS,
        1],
    ["HP UP",
        "ITEM_HP_UP",
        Pocket.POCKET_ITEMS,
        2],
    ["PROTEIN",
        "ITEM_PROTEIN",
        Pocket.POCKET_ITEMS,
        2],
    ["IRON",
        "ITEM_IRON",
        Pocket.POCKET_ITEMS,
        2],
    ["CARBOS",
        "ITEM_CARBOS",
        Pocket.POCKET_ITEMS,
        2],
    ["CALCIUM",
        "ITEM_CALCIUM",
        Pocket.POCKET_ITEMS,
        2],
    ["RARE CANDY",
        "ITEM_RARE_CANDY",
        Pocket.POCKET_ITEMS,
        2],
    ["PP UP",
        "ITEM_PP_UP",
        Pocket.POCKET_ITEMS,
        2],
    ["ZINC",
        "ITEM_ZINC",
        Pocket.POCKET_ITEMS,
        2],
    ["PP MAX",
        "ITEM_PP_MAX",
        Pocket.POCKET_ITEMS,
        1],
    ["GUARD SPEC.",
        "ITEM_GUARD_SPEC",
        Pocket.POCKET_ITEMS,
        1],
    ["DIRE HIT",
        "ITEM_DIRE_HIT",
        Pocket.POCKET_ITEMS,
        1],
    ["X ATTACK",
        "ITEM_X_ATTACK",
        Pocket.POCKET_ITEMS,
        1],
    ["X DEFEND",
        "ITEM_X_DEFEND",
        Pocket.POCKET_ITEMS,
        1],
    ["X SPEED",
        "ITEM_X_SPEED",
        Pocket.POCKET_ITEMS,
        1],
    ["X ACCURACY",
        "ITEM_X_ACCURACY",
        Pocket.POCKET_ITEMS,
        1],
    ["X SPECIAL",
        "ITEM_X_SPECIAL",
        Pocket.POCKET_ITEMS,
        1],
    ["POKé DOLL",
        "ITEM_POKE_DOLL",
        Pocket.POCKET_ITEMS,
        1],
    ["FLUFFY TAIL",
        "ITEM_FLUFFY_TAIL",
        Pocket.POCKET_ITEMS,
        1],
    ["SUPER REPEL",
        "ITEM_SUPER_REPEL",
        Pocket.POCKET_ITEMS,
        1],
    ["MAX REPEL",
        "ITEM_MAX_REPEL",
        Pocket.POCKET_ITEMS,
        1],
    # ["ESCAPE ROPE",
    #     "ITEM_ESCAPE_ROPE",
    #     Pocket.POCKET_ITEMS,
    #     1],
    ["REPEL",
        "ITEM_REPEL",
        Pocket.POCKET_ITEMS,
        1],
    ["SUN STONE",
        "ITEM_SUN_STONE",
        Pocket.POCKET_ITEMS,
        1],
    ["MOON STONE",
        "ITEM_MOON_STONE",
        Pocket.POCKET_ITEMS,
        1],
    ["FIRE STONE",
        "ITEM_FIRE_STONE",
        Pocket.POCKET_ITEMS,
        1],
    ["THUNDERSTONE",
        "ITEM_THUNDER_STONE",
        Pocket.POCKET_ITEMS,
        1],
    ["WATER STONE",
        "ITEM_WATER_STONE",
        Pocket.POCKET_ITEMS,
        1],
    ["LEAF STONE",
        "ITEM_LEAF_STONE",
        Pocket.POCKET_ITEMS,
        1],
    ["TINYMUSHROOM",
        "ITEM_TINY_MUSHROOM",
        Pocket.POCKET_ITEMS,
        1],
    ["BIG MUSHROOM",
        "ITEM_BIG_MUSHROOM",
        Pocket.POCKET_ITEMS,
        1],
    ["PEARL",
        "ITEM_PEARL",
        Pocket.POCKET_ITEMS,
        1],
    ["BIG PEARL",
        "ITEM_BIG_PEARL",
        Pocket.POCKET_ITEMS,
        1],
    ["STARDUST",
        "ITEM_STARDUST",
        Pocket.POCKET_ITEMS,
        1],
    ["STAR PIECE",
        "ITEM_STAR_PIECE",
        Pocket.POCKET_ITEMS,
        1],
    ["NUGGET",
        "ITEM_NUGGET",
        Pocket.POCKET_ITEMS,
        1],
    ["HEART SCALE",
        "ITEM_HEART_SCALE",
        Pocket.POCKET_ITEMS,
        1],
    ["CHERI BERRY",
        "ITEM_CHERI_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["CHESTO BERRY",
        "ITEM_CHESTO_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["PECHA BERRY",
        "ITEM_PECHA_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["RAWST BERRY",
        "ITEM_RAWST_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["ASPEAR BERRY",
        "ITEM_ASPEAR_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["LEPPA BERRY",
        "ITEM_LEPPA_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["ORAN BERRY",
        "ITEM_ORAN_BERRY",
        Pocket.POCKET_BERRIES,
        4],
    ["PERSIM BERRY",
        "ITEM_PERSIM_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["LUM BERRY",
        "ITEM_LUM_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["SITRUS BERRY",
        "ITEM_SITRUS_BERRY",
        Pocket.POCKET_BERRIES,
        3],
    ["FIGY BERRY",
        "ITEM_FIGY_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["WIKI BERRY",
        "ITEM_WIKI_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["MAGO BERRY",
        "ITEM_MAGO_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["AGUAV BERRY",
        "ITEM_AGUAV_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["IAPAPA BERRY",
        "ITEM_IAPAPA_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["RAZZ BERRY",
        "ITEM_RAZZ_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["BLUK BERRY",
        "ITEM_BLUK_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["NANAB BERRY",
        "ITEM_NANAB_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["WEPEAR BERRY",
        "ITEM_WEPEAR_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["PINAP BERRY",
        "ITEM_PINAP_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["POMEG BERRY",
        "ITEM_POMEG_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["KELPSY BERRY",
        "ITEM_KELPSY_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["QUALOT BERRY",
        "ITEM_QUALOT_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["HONDEW BERRY",
        "ITEM_HONDEW_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["GREPA BERRY",
        "ITEM_GREPA_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["TAMATO BERRY",
        "ITEM_TAMATO_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["CORNN BERRY",
        "ITEM_CORNN_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["MAGOST BERRY",
        "ITEM_MAGOST_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["RABUTA BERRY",
        "ITEM_RABUTA_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["NOMEL BERRY",
        "ITEM_NOMEL_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["SPELON BERRY",
        "ITEM_SPELON_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["PAMTRE BERRY",
        "ITEM_PAMTRE_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["WATMEL BERRY",
        "ITEM_WATMEL_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["DURIN BERRY",
        "ITEM_DURIN_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["BELUE BERRY",
        "ITEM_BELUE_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["LIECHI BERRY",
        "ITEM_LIECHI_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["GANLON BERRY",
        "ITEM_GANLON_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["SALAC BERRY",
        "ITEM_SALAC_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["PETAYA BERRY",
        "ITEM_PETAYA_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["APICOT BERRY",
        "ITEM_APICOT_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["LANSAT BERRY",
        "ITEM_LANSAT_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["STARF BERRY",
        "ITEM_STARF_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["ENIGMA BERRY",
        "ITEM_ENIGMA_BERRY",
        Pocket.POCKET_BERRIES,
        1],
    ["BRIGHTPOWDER",
        "ITEM_BRIGHT_POWDER",
        Pocket.POCKET_ITEMS,
        1],
    ["WHITE HERB",
        "ITEM_WHITE_HERB",
        Pocket.POCKET_ITEMS,
        1],
    ["MACHO BRACE",
        "ITEM_MACHO_BRACE",
        Pocket.POCKET_ITEMS,
        1],
    ["EXP. SHARE",
        "ITEM_EXP_SHARE",
        Pocket.POCKET_ITEMS,
        2],
    ["QUICK CLAW",
        "ITEM_QUICK_CLAW",
        Pocket.POCKET_ITEMS,
        1],
    ["SOOTHE BELL",
        "ITEM_SOOTHE_BELL",
        Pocket.POCKET_ITEMS,
        1],
    ["MENTAL HERB",
        "ITEM_MENTAL_HERB",
        Pocket.POCKET_ITEMS,
        1],
    ["CHOICE BAND",
        "ITEM_CHOICE_BAND",
        Pocket.POCKET_ITEMS,
        1],
    ["KING'S ROCK",
        "ITEM_KINGS_ROCK",
        Pocket.POCKET_ITEMS,
        1],
    ["SILVERPOWDER",
        "ITEM_SILVER_POWDER",
        Pocket.POCKET_ITEMS,
        1],
    ["AMULET COIN",
        "ITEM_AMULET_COIN",
        Pocket.POCKET_ITEMS,
        1],
    ["CLEANSE TAG",
        "ITEM_CLEANSE_TAG",
        Pocket.POCKET_ITEMS,
        1],
    ["SOUL DEW",
        "ITEM_SOUL_DEW",
        Pocket.POCKET_ITEMS,
        1],
    ["DEEPSEATOOTH",
        "ITEM_DEEP_SEA_TOOTH",
        Pocket.POCKET_ITEMS,
        1],
    ["DEEPSEASCALE",
        "ITEM_DEEP_SEA_SCALE",
        Pocket.POCKET_ITEMS,
        1],
    ["SMOKE BALL",
        "ITEM_SMOKE_BALL",
        Pocket.POCKET_ITEMS,
        1],
    ["EVERSTONE",
        "ITEM_EVERSTONE",
        Pocket.POCKET_ITEMS,
        1],
    ["FOCUS BAND",
        "ITEM_FOCUS_BAND",
        Pocket.POCKET_ITEMS,
        1],
    ["LUCKY EGG",
        "ITEM_LUCKY_EGG",
        Pocket.POCKET_ITEMS,
        1],
    ["SCOPE LENS",
        "ITEM_SCOPE_LENS",
        Pocket.POCKET_ITEMS,
        1],
    ["METAL COAT",
        "ITEM_METAL_COAT",
        Pocket.POCKET_ITEMS,
        1],
    ["LEFTOVERS",
        "ITEM_LEFTOVERS",
        Pocket.POCKET_ITEMS,
        2],
    ["DRAGON SCALE",
        "ITEM_DRAGON_SCALE",
        Pocket.POCKET_ITEMS,
        1],
    ["LIGHT BALL",
        "ITEM_LIGHT_BALL",
        Pocket.POCKET_ITEMS,
        1],
    ["SOFT SAND",
        "ITEM_SOFT_SAND",
        Pocket.POCKET_ITEMS,
        1],
    ["HARD STONE",
        "ITEM_HARD_STONE",
        Pocket.POCKET_ITEMS,
        1],
    ["MIRACLE SEED",
        "ITEM_MIRACLE_SEED",
        Pocket.POCKET_ITEMS,
        1],
    ["BLACKGLASSES",
        "ITEM_BLACK_GLASSES",
        Pocket.POCKET_ITEMS,
        1],
    ["BLACK BELT",
        "ITEM_BLACK_BELT",
        Pocket.POCKET_ITEMS,
        1],
    ["MAGNET",
        "ITEM_MAGNET",
        Pocket.POCKET_ITEMS,
        1],
    ["MYSTIC WATER",
        "ITEM_MYSTIC_WATER",
        Pocket.POCKET_ITEMS,
        1],
    ["SHARP BEAK",
        "ITEM_SHARP_BEAK",
        Pocket.POCKET_ITEMS,
        1],
    ["POISON BARB",
        "ITEM_POISON_BARB",
        Pocket.POCKET_ITEMS,
        1],
    ["NEVERMELTICE",
        "ITEM_NEVER_MELT_ICE",
        Pocket.POCKET_ITEMS,
        1],
    ["SPELL TAG",
        "ITEM_SPELL_TAG",
        Pocket.POCKET_ITEMS,
        1],
    ["TWISTEDSPOON",
        "ITEM_TWISTED_SPOON",
        Pocket.POCKET_ITEMS,
        1],
    ["CHARCOAL",
        "ITEM_CHARCOAL",
        Pocket.POCKET_ITEMS,
        1],
    ["DRAGON FANG",
        "ITEM_DRAGON_FANG",
        Pocket.POCKET_ITEMS,
        1],
    ["SILK SCARF",
        "ITEM_SILK_SCARF",
        Pocket.POCKET_ITEMS,
        1],
    ["UP-GRADE",
        "ITEM_UP_GRADE",
        Pocket.POCKET_ITEMS,
        1],
    ["SHELL BELL",
        "ITEM_SHELL_BELL",
        Pocket.POCKET_ITEMS,
        1],
    ["SEA INCENSE",
        "ITEM_SEA_INCENSE",
        Pocket.POCKET_ITEMS,
        1],
    ["LAX INCENSE",
        "ITEM_LAX_INCENSE",
        Pocket.POCKET_ITEMS,
        1],
    ["LUCKY PUNCH",
        "ITEM_LUCKY_PUNCH",
        Pocket.POCKET_ITEMS,
        1],
    ["METAL POWDER",
        "ITEM_METAL_POWDER",
        Pocket.POCKET_ITEMS,
        1],
    ["THICK CLUB",
        "ITEM_THICK_CLUB",
        Pocket.POCKET_ITEMS,
        1],
    ["STICK",
        "ITEM_STICK",
        Pocket.POCKET_ITEMS,
        1],
    ["RED SCARF",
        "ITEM_RED_SCARF",
        Pocket.POCKET_ITEMS,
        1],
    ["BLUE SCARF",
        "ITEM_BLUE_SCARF",
        Pocket.POCKET_ITEMS,
        1],
    ["PINK SCARF",
        "ITEM_PINK_SCARF",
        Pocket.POCKET_ITEMS,
        1],
    ["GREEN SCARF",
        "ITEM_GREEN_SCARF",
        Pocket.POCKET_ITEMS,
        1],
    ["YELLOW SCARF",
        "ITEM_YELLOW_SCARF",
        Pocket.POCKET_ITEMS,
        1],
    ["OLD ROD",
        "ITEM_OLD_ROD",
        Pocket.POCKET_KEY_ITEMS,
        1],
    ["TM01",
        "ITEM_TM01_FOCUS_PUNCH",
        Pocket.POCKET_TM_HM,
        1],
    ["TM02",
        "ITEM_TM02_DRAGON_CLAW",
        Pocket.POCKET_TM_HM,
        1],
    ["TM03",
        "ITEM_TM03_WATER_PULSE",
        Pocket.POCKET_TM_HM,
        1],
    ["TM04",
        "ITEM_TM04_CALM_MIND",
        Pocket.POCKET_TM_HM,
        1],
    ["TM05",
        "ITEM_TM05_ROAR",
        Pocket.POCKET_TM_HM,
        1],
    ["TM06",
        "ITEM_TM06_TOXIC",
        Pocket.POCKET_TM_HM,
        1],
    ["TM07",
        "ITEM_TM07_HAIL",
        Pocket.POCKET_TM_HM,
        1],
    ["TM08",
        "ITEM_TM08_BULK_UP",
        Pocket.POCKET_TM_HM,
        1],
    ["TM09",
        "ITEM_TM09_BULLET_SEED",
        Pocket.POCKET_TM_HM,
        1],
    ["TM10",
        "ITEM_TM10_HIDDEN_POWER",
        Pocket.POCKET_TM_HM,
        1],
    ["TM11",
        "ITEM_TM11_SUNNY_DAY",
        Pocket.POCKET_TM_HM,
        1],
    ["TM12",
        "ITEM_TM12_TAUNT",
        Pocket.POCKET_TM_HM,
        1],
    ["TM13",
        "ITEM_TM13_ICE_BEAM",
        Pocket.POCKET_TM_HM,
        1],
    ["TM14",
        "ITEM_TM14_BLIZZARD",
        Pocket.POCKET_TM_HM,
        1],
    ["TM15",
        "ITEM_TM15_HYPER_BEAM",
        Pocket.POCKET_TM_HM,
        1],
    ["TM16",
        "ITEM_TM16_LIGHT_SCREEN",
        Pocket.POCKET_TM_HM,
        1],
    ["TM17",
        "ITEM_TM17_PROTECT",
        Pocket.POCKET_TM_HM,
        1],
    ["TM18",
        "ITEM_TM18_RAIN_DANCE",
        Pocket.POCKET_TM_HM,
        1],
    ["TM19",
        "ITEM_TM19_GIGA_DRAIN",
        Pocket.POCKET_TM_HM,
        1],
    ["TM20",
        "ITEM_TM20_SAFEGUARD",
        Pocket.POCKET_TM_HM,
        1],
    ["TM21",
        "ITEM_TM21_FRUSTRATION",
        Pocket.POCKET_TM_HM,
        1],
    ["TM22",
        "ITEM_TM22_SOLARBEAM",
        Pocket.POCKET_TM_HM,
        1],
    ["TM23",
        "ITEM_TM23_IRON_TAIL",
        Pocket.POCKET_TM_HM,
        1],
    ["TM24",
        "ITEM_TM24_THUNDERBOLT",
        Pocket.POCKET_TM_HM,
        1],
    ["TM25",
        "ITEM_TM25_THUNDER",
        Pocket.POCKET_TM_HM,
        1],
    ["TM26",
        "ITEM_TM26_EARTHQUAKE",
        Pocket.POCKET_TM_HM,
        1],
    ["TM27",
        "ITEM_TM27_RETURN",
        Pocket.POCKET_TM_HM,
        1],
    ["TM28",
        "ITEM_TM28_DIG",
        Pocket.POCKET_TM_HM,
        1],
    ["TM29",
        "ITEM_TM29_PSYCHIC",
        Pocket.POCKET_TM_HM,
        1],
    ["TM30",
        "ITEM_TM30_SHADOW_BALL",
        Pocket.POCKET_TM_HM,
        1],
    ["TM31",
        "ITEM_TM31_BRICK_BREAK",
        Pocket.POCKET_TM_HM,
        1],
    ["TM32",
        "ITEM_TM32_DOUBLE_TEAM",
        Pocket.POCKET_TM_HM,
        1],
    ["TM33",
        "ITEM_TM33_REFLECT",
        Pocket.POCKET_TM_HM,
        1],
    ["TM34",
        "ITEM_TM34_SHOCK_WAVE",
        Pocket.POCKET_TM_HM,
        1],
    ["TM35",
        "ITEM_TM35_FLAMETHROWER",
        Pocket.POCKET_TM_HM,
        1],
    ["TM36",
        "ITEM_TM36_SLUDGE_BOMB",
        Pocket.POCKET_TM_HM,
        1],
    ["TM37",
        "ITEM_TM37_SANDSTORM",
        Pocket.POCKET_TM_HM,
        1],
    ["TM38",
        "ITEM_TM38_FIRE_BLAST",
        Pocket.POCKET_TM_HM,
        1],
    ["TM39",
        "ITEM_TM39_ROCK_TOMB",
        Pocket.POCKET_TM_HM,
        1],
    ["TM40",
        "ITEM_TM40_AERIAL_ACE",
        Pocket.POCKET_TM_HM,
        1],
    ["TM41",
        "ITEM_TM41_TORMENT",
        Pocket.POCKET_TM_HM,
        1],
    ["TM42",
        "ITEM_TM42_FACADE",
        Pocket.POCKET_TM_HM,
        1],
    ["TM43",
        "ITEM_TM43_SECRET_POWER",
        Pocket.POCKET_TM_HM,
        1],
    ["TM44",
        "ITEM_TM44_REST",
        Pocket.POCKET_TM_HM,
        1],
    ["TM45",
        "ITEM_TM45_ATTRACT",
        Pocket.POCKET_TM_HM,
        1],
    ["TM46",
        "ITEM_TM46_THIEF",
        Pocket.POCKET_TM_HM,
        1],
    ["TM47",
        "ITEM_TM47_STEEL_WING",
        Pocket.POCKET_TM_HM,
        1],
    ["TM48",
        "ITEM_TM48_SKILL_SWAP",
        Pocket.POCKET_TM_HM,
        1],
    ["TM49",
        "ITEM_TM49_SNATCH",
        Pocket.POCKET_TM_HM,
        1],
    ["TM50",
        "ITEM_TM50_OVERHEAT",
        Pocket.POCKET_TM_HM,
        1],
    ["HM01",
        "ITEM_HM01_CUT",
        Pocket.POCKET_TM_HM,
        1],
    ["HM02",
        "ITEM_HM02_FLY",
        Pocket.POCKET_TM_HM,
        1],
    ["HM03",
        "ITEM_HM03_SURF",
        Pocket.POCKET_TM_HM,
        1],
    ["HM04",
        "ITEM_HM04_STRENGTH",
        Pocket.POCKET_TM_HM,
        1],
    ["HM05",
        "ITEM_HM05_FLASH",
        Pocket.POCKET_TM_HM,
        1],
    ["HM06",
        "ITEM_HM06_ROCK_SMASH",
        Pocket.POCKET_TM_HM,
        1],
    ["HM07",
        "ITEM_HM07_WATERFALL",
        Pocket.POCKET_TM_HM,
        1],
    ["HM08",
        "ITEM_HM08_DIVE",
        Pocket.POCKET_TM_HM,
        1]]

def computeWeights():
    global POCKET_WEIGHT, TOTAL_WEIGHT, ALL_ITEMS
    TOTAL_WEIGHT = 0
    for item in ALL_ITEMS:
        POCKET_WEIGHT[item[2]] += item[3]
    for weight in POCKET_WEIGHT:
        TOTAL_WEIGHT = TOTAL_WEIGHT + weight

def getByWeight(list, w):
    """Returns the item corresponding to the int w where item[3] is its weight."""
    itemId = 0
    partialWeight = list[0][3]
    while partialWeight < w:
        itemId += 1
        partialWeight += list[itemId][3]
    return list[itemId]

def getRandomItem():
    """Returns a random item."""
    randomId = random.randint(1, TOTAL_WEIGHT)
    return getByWeight(ALL_ITEMS, randomId)[1]

def getRandomItemOf(pocket):
    """Returns a random item of given pocket."""
    item_pocket = [item for item in ALL_ITEMS if item[2] == pocket]
    randomId = random.randint(1, POCKET_WEIGHT[pocket])
    return getByWeight(item_pocket, randomId)[1]
    