from enum import IntEnum
import random

global ALL_POKE

class Type(IntEnum):
    """Enumeration for the different pokemon types."""
    TYPE_NORMAL = 1
    TYPE_FIGHTING = 2
    TYPE_FLYING = 3
    TYPE_POISON = 4
    TYPE_GROUND = 5
    TYPE_ROCK = 6
    TYPE_BUG = 7
    TYPE_GHOST = 8
    TYPE_STEEL = 9
    TYPE_FIRE = 10
    TYPE_WATER = 11
    TYPE_GRASS = 12
    TYPE_ELECTRIC = 13
    TYPE_PSYCHIC = 14
    TYPE_ICE = 15
    TYPE_DRAGON = 16
    TYPE_DARK = 17

ALL_POKE = [
    [ "SPECIES_BULBASAUR",
    Type.TYPE_GRASS,
    Type.TYPE_POISON ],
    [ "SPECIES_IVYSAUR",
    Type.TYPE_GRASS,
    Type.TYPE_POISON ],
    [ "SPECIES_VENUSAUR",
    Type.TYPE_GRASS,
    Type.TYPE_POISON ],
    [ "SPECIES_CHARMANDER",
    Type.TYPE_FIRE,
    Type.TYPE_FIRE ],
    [ "SPECIES_CHARMELEON",
    Type.TYPE_FIRE,
    Type.TYPE_FIRE ],
    [ "SPECIES_CHARIZARD",
    Type.TYPE_FIRE,
    Type.TYPE_FLYING ],
    [ "SPECIES_SQUIRTLE",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_WARTORTLE",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_BLASTOISE",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_CATERPIE",
    Type.TYPE_BUG,
    Type.TYPE_BUG ],
    [ "SPECIES_METAPOD",
    Type.TYPE_BUG,
    Type.TYPE_BUG ],
    [ "SPECIES_BUTTERFREE",
    Type.TYPE_BUG,
    Type.TYPE_FLYING ],
    [ "SPECIES_WEEDLE",
    Type.TYPE_BUG,
    Type.TYPE_POISON ],
    [ "SPECIES_KAKUNA",
    Type.TYPE_BUG,
    Type.TYPE_POISON ],
    [ "SPECIES_BEEDRILL",
    Type.TYPE_BUG,
    Type.TYPE_POISON ],
    [ "SPECIES_PIDGEY",
    Type.TYPE_NORMAL,
    Type.TYPE_FLYING ],
    [ "SPECIES_PIDGEOTTO",
    Type.TYPE_NORMAL,
    Type.TYPE_FLYING ],
    [ "SPECIES_PIDGEOT",
    Type.TYPE_NORMAL,
    Type.TYPE_FLYING ],
    [ "SPECIES_RATTATA",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_RATICATE",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_SPEAROW",
    Type.TYPE_NORMAL,
    Type.TYPE_FLYING ],
    [ "SPECIES_FEAROW",
    Type.TYPE_NORMAL,
    Type.TYPE_FLYING ],
    [ "SPECIES_EKANS",
    Type.TYPE_POISON,
    Type.TYPE_POISON ],
    [ "SPECIES_ARBOK",
    Type.TYPE_POISON,
    Type.TYPE_POISON ],
    [ "SPECIES_PIKACHU",
    Type.TYPE_ELECTRIC,
    Type.TYPE_ELECTRIC ],
    [ "SPECIES_RAICHU",
    Type.TYPE_ELECTRIC,
    Type.TYPE_ELECTRIC ],
    [ "SPECIES_SANDSHREW",
    Type.TYPE_GROUND,
    Type.TYPE_GROUND ],
    [ "SPECIES_SANDSLASH",
    Type.TYPE_GROUND,
    Type.TYPE_GROUND ],
    [ "SPECIES_NIDORAN_F",
    Type.TYPE_POISON,
    Type.TYPE_POISON ],
    [ "SPECIES_NIDORINA",
    Type.TYPE_POISON,
    Type.TYPE_POISON ],
    [ "SPECIES_NIDOQUEEN",
    Type.TYPE_POISON,
    Type.TYPE_GROUND ],
    [ "SPECIES_NIDORAN_M", 
    Type.TYPE_POISON,
    Type.TYPE_POISON ],
    [ "SPECIES_NIDORINO",
    Type.TYPE_POISON,
    Type.TYPE_POISON ],
    [ "SPECIES_NIDOKING",
    Type.TYPE_POISON,
    Type.TYPE_GROUND ],
    [ "SPECIES_CLEFAIRY",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_CLEFABLE",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_VULPIX",
    Type.TYPE_FIRE,
    Type.TYPE_FIRE ],
    [ "SPECIES_NINETALES",
    Type.TYPE_FIRE,
    Type.TYPE_FIRE ],
    [ "SPECIES_JIGGLYPUFF",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_WIGGLYTUFF",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_ZUBAT",
    Type.TYPE_POISON,
    Type.TYPE_FLYING ],
    [ "SPECIES_GOLBAT",
    Type.TYPE_POISON,
    Type.TYPE_FLYING ],
    [ "SPECIES_ODDISH",
    Type.TYPE_GRASS,
    Type.TYPE_POISON ],
    [ "SPECIES_GLOOM",
    Type.TYPE_GRASS,
    Type.TYPE_POISON ],
    [ "SPECIES_VILEPLUME",
    Type.TYPE_GRASS,
    Type.TYPE_POISON ],
    [ "SPECIES_PARAS",
    Type.TYPE_BUG,
    Type.TYPE_GRASS ],
    [ "SPECIES_PARASECT",
    Type.TYPE_BUG,
    Type.TYPE_GRASS ],
    [ "SPECIES_VENONAT",
    Type.TYPE_BUG,
    Type.TYPE_POISON ],
    [ "SPECIES_VENOMOTH",
    Type.TYPE_BUG,
    Type.TYPE_POISON ],
    [ "SPECIES_DIGLETT",
    Type.TYPE_GROUND,
    Type.TYPE_GROUND ],
    [ "SPECIES_DUGTRIO",
    Type.TYPE_GROUND,
    Type.TYPE_GROUND ],
    [ "SPECIES_MEOWTH",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_PERSIAN",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_PSYDUCK",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_GOLDUCK",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_MANKEY",
    Type.TYPE_FIGHTING,
    Type.TYPE_FIGHTING ],
    [ "SPECIES_PRIMEAPE",
    Type.TYPE_FIGHTING,
    Type.TYPE_FIGHTING ],
    [ "SPECIES_GROWLITHE",
    Type.TYPE_FIRE,
    Type.TYPE_FIRE ],
    [ "SPECIES_ARCANINE",
    Type.TYPE_FIRE,
    Type.TYPE_FIRE ],
    [ "SPECIES_POLIWAG",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_POLIWHIRL",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_POLIWRATH",
    Type.TYPE_WATER,
    Type.TYPE_FIGHTING ],
    [ "SPECIES_ABRA",
    Type.TYPE_PSYCHIC,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_KADABRA",
    Type.TYPE_PSYCHIC,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_ALAKAZAM",
    Type.TYPE_PSYCHIC,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_MACHOP",
    Type.TYPE_FIGHTING,
    Type.TYPE_FIGHTING ],
    [ "SPECIES_MACHOKE",
    Type.TYPE_FIGHTING,
    Type.TYPE_FIGHTING ],
    [ "SPECIES_MACHAMP",
    Type.TYPE_FIGHTING,
    Type.TYPE_FIGHTING ],
    [ "SPECIES_BELLSPROUT",
    Type.TYPE_GRASS,
    Type.TYPE_POISON ],
    [ "SPECIES_WEEPINBELL",
    Type.TYPE_GRASS,
    Type.TYPE_POISON ],
    [ "SPECIES_VICTREEBEL",
    Type.TYPE_GRASS,
    Type.TYPE_POISON ],
    [ "SPECIES_TENTACOOL",
    Type.TYPE_WATER,
    Type.TYPE_POISON ],
    [ "SPECIES_TENTACRUEL",
    Type.TYPE_WATER,
    Type.TYPE_POISON ],
    [ "SPECIES_GEODUDE",
    Type.TYPE_ROCK,
    Type.TYPE_GROUND ],
    [ "SPECIES_GRAVELER",
    Type.TYPE_ROCK,
    Type.TYPE_GROUND ],
    [ "SPECIES_GOLEM",
    Type.TYPE_ROCK,
    Type.TYPE_GROUND ],
    [ "SPECIES_PONYTA",
    Type.TYPE_FIRE,
    Type.TYPE_FIRE ],
    [ "SPECIES_RAPIDASH",
    Type.TYPE_FIRE,
    Type.TYPE_FIRE ],
    [ "SPECIES_SLOWPOKE",
    Type.TYPE_WATER,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_SLOWBRO",
    Type.TYPE_WATER,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_MAGNEMITE",
    Type.TYPE_ELECTRIC,
    Type.TYPE_STEEL ],
    [ "SPECIES_MAGNETON",
    Type.TYPE_ELECTRIC,
    Type.TYPE_STEEL ],
    [ "SPECIES_FARFETCHD",
    Type.TYPE_NORMAL,
    Type.TYPE_FLYING ],
    [ "SPECIES_DODUO",
    Type.TYPE_NORMAL,
    Type.TYPE_FLYING ],
    [ "SPECIES_DODRIO",
    Type.TYPE_NORMAL,
    Type.TYPE_FLYING ],
    [ "SPECIES_SEEL",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_DEWGONG",
    Type.TYPE_WATER,
    Type.TYPE_ICE ],
    [ "SPECIES_GRIMER",
    Type.TYPE_POISON,
    Type.TYPE_POISON ],
    [ "SPECIES_MUK",
    Type.TYPE_POISON,
    Type.TYPE_POISON ],
    [ "SPECIES_SHELLDER",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_CLOYSTER",
    Type.TYPE_WATER,
    Type.TYPE_ICE ],
    [ "SPECIES_GASTLY",
    Type.TYPE_GHOST,
    Type.TYPE_POISON ],
    [ "SPECIES_HAUNTER",
    Type.TYPE_GHOST,
    Type.TYPE_POISON ],
    [ "SPECIES_GENGAR",
    Type.TYPE_GHOST,
    Type.TYPE_POISON ],
    [ "SPECIES_ONIX",
    Type.TYPE_ROCK,
    Type.TYPE_GROUND ],
    [ "SPECIES_DROWZEE",
    Type.TYPE_PSYCHIC,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_HYPNO",
    Type.TYPE_PSYCHIC,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_KRABBY",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_KINGLER",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_VOLTORB",
    Type.TYPE_ELECTRIC,
    Type.TYPE_ELECTRIC ],
    [ "SPECIES_ELECTRODE",
    Type.TYPE_ELECTRIC,
    Type.TYPE_ELECTRIC ],
    [ "SPECIES_EXEGGCUTE",
    Type.TYPE_GRASS,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_EXEGGUTOR",
    Type.TYPE_GRASS,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_CUBONE",
    Type.TYPE_GROUND,
    Type.TYPE_GROUND ],
    [ "SPECIES_MAROWAK",
    Type.TYPE_GROUND,
    Type.TYPE_GROUND ],
    [ "SPECIES_HITMONLEE",
    Type.TYPE_FIGHTING,
    Type.TYPE_FIGHTING ],
    [ "SPECIES_HITMONCHAN",
    Type.TYPE_FIGHTING,
    Type.TYPE_FIGHTING ],
    [ "SPECIES_LICKITUNG",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_KOFFING",
    Type.TYPE_POISON,
    Type.TYPE_POISON ],
    [ "SPECIES_WEEZING",
    Type.TYPE_POISON,
    Type.TYPE_POISON ],
    [ "SPECIES_RHYHORN",
    Type.TYPE_GROUND,
    Type.TYPE_ROCK ],
    [ "SPECIES_RHYDON",
    Type.TYPE_GROUND,
    Type.TYPE_ROCK ],
    [ "SPECIES_CHANSEY",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_TANGELA",
    Type.TYPE_GRASS,
    Type.TYPE_GRASS ],
    [ "SPECIES_KANGASKHAN",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_HORSEA",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_SEADRA",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_GOLDEEN",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_SEAKING",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_STARYU",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_STARMIE",
    Type.TYPE_WATER,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_MR_MIME",
    Type.TYPE_PSYCHIC,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_SCYTHER",
    Type.TYPE_BUG,
    Type.TYPE_FLYING ],
    [ "SPECIES_JYNX",
    Type.TYPE_ICE,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_ELECTABUZZ",
    Type.TYPE_ELECTRIC,
    Type.TYPE_ELECTRIC ],
    [ "SPECIES_MAGMAR",
    Type.TYPE_FIRE,
    Type.TYPE_FIRE ],
    [ "SPECIES_PINSIR",
    Type.TYPE_BUG,
    Type.TYPE_BUG ],
    [ "SPECIES_TAUROS",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_MAGIKARP",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_GYARADOS",
    Type.TYPE_WATER,
    Type.TYPE_FLYING ],
    [ "SPECIES_LAPRAS",
    Type.TYPE_WATER,
    Type.TYPE_ICE ],
    [ "SPECIES_DITTO",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_EEVEE",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_VAPOREON",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_JOLTEON",
    Type.TYPE_ELECTRIC,
    Type.TYPE_ELECTRIC ],
    [ "SPECIES_FLAREON",
    Type.TYPE_FIRE,
    Type.TYPE_FIRE ],
    [ "SPECIES_PORYGON",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OMANYTE",
    Type.TYPE_ROCK,
    Type.TYPE_WATER ],
    [ "SPECIES_OMASTAR",
    Type.TYPE_ROCK,
    Type.TYPE_WATER ],
    [ "SPECIES_KABUTO",
    Type.TYPE_ROCK,
    Type.TYPE_WATER ],
    [ "SPECIES_KABUTOPS",
    Type.TYPE_ROCK,
    Type.TYPE_WATER ],
    [ "SPECIES_AERODACTYL",
    Type.TYPE_ROCK,
    Type.TYPE_FLYING ],
    [ "SPECIES_SNORLAX",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_ARTICUNO",
    Type.TYPE_ICE,
    Type.TYPE_FLYING ],
    [ "SPECIES_ZAPDOS",
    Type.TYPE_ELECTRIC,
    Type.TYPE_FLYING ],
    [ "SPECIES_MOLTRES",
    Type.TYPE_FIRE,
    Type.TYPE_FLYING ],
    [ "SPECIES_DRATINI",
    Type.TYPE_DRAGON,
    Type.TYPE_DRAGON ],
    [ "SPECIES_DRAGONAIR",
    Type.TYPE_DRAGON,
    Type.TYPE_DRAGON ],
    [ "SPECIES_DRAGONITE",
    Type.TYPE_DRAGON,
    Type.TYPE_FLYING ],
    [ "SPECIES_MEWTWO",
    Type.TYPE_PSYCHIC,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_MEW",
    Type.TYPE_PSYCHIC,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_CHIKORITA",
    Type.TYPE_GRASS,
    Type.TYPE_GRASS ],
    [ "SPECIES_BAYLEEF",
    Type.TYPE_GRASS,
    Type.TYPE_GRASS ],
    [ "SPECIES_MEGANIUM",
    Type.TYPE_GRASS,
    Type.TYPE_GRASS ],
    [ "SPECIES_CYNDAQUIL",
    Type.TYPE_FIRE,
    Type.TYPE_FIRE ],
    [ "SPECIES_QUILAVA",
    Type.TYPE_FIRE,
    Type.TYPE_FIRE ],
    [ "SPECIES_TYPHLOSION",
    Type.TYPE_FIRE,
    Type.TYPE_FIRE ],
    [ "SPECIES_TOTODILE",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_CROCONAW",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_FERALIGATR",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_SENTRET",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_FURRET",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_HOOTHOOT",
    Type.TYPE_NORMAL,
    Type.TYPE_FLYING ],
    [ "SPECIES_NOCTOWL",
    Type.TYPE_NORMAL,
    Type.TYPE_FLYING ],
    [ "SPECIES_LEDYBA",
    Type.TYPE_BUG,
    Type.TYPE_FLYING ],
    [ "SPECIES_LEDIAN",
    Type.TYPE_BUG,
    Type.TYPE_FLYING ],
    [ "SPECIES_SPINARAK",
    Type.TYPE_BUG,
    Type.TYPE_POISON ],
    [ "SPECIES_ARIADOS",
    Type.TYPE_BUG,
    Type.TYPE_POISON ],
    [ "SPECIES_CROBAT",
    Type.TYPE_POISON,
    Type.TYPE_FLYING ],
    [ "SPECIES_CHINCHOU",
    Type.TYPE_WATER,
    Type.TYPE_ELECTRIC ],
    [ "SPECIES_LANTURN",
    Type.TYPE_WATER,
    Type.TYPE_ELECTRIC ],
    [ "SPECIES_PICHU",
    Type.TYPE_ELECTRIC,
    Type.TYPE_ELECTRIC ],
    [ "SPECIES_CLEFFA",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_IGGLYBUFF",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_TOGEPI",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_TOGETIC",
    Type.TYPE_NORMAL,
    Type.TYPE_FLYING ],
    [ "SPECIES_NATU",
    Type.TYPE_PSYCHIC,
    Type.TYPE_FLYING ],
    [ "SPECIES_XATU",
    Type.TYPE_PSYCHIC,
    Type.TYPE_FLYING ],
    [ "SPECIES_MAREEP",
    Type.TYPE_ELECTRIC,
    Type.TYPE_ELECTRIC ],
    [ "SPECIES_FLAAFFY",
    Type.TYPE_ELECTRIC,
    Type.TYPE_ELECTRIC ],
    [ "SPECIES_AMPHAROS",
    Type.TYPE_ELECTRIC,
    Type.TYPE_ELECTRIC ],
    [ "SPECIES_BELLOSSOM",
    Type.TYPE_GRASS,
    Type.TYPE_GRASS ],
    [ "SPECIES_MARILL",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_AZUMARILL",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_SUDOWOODO",
    Type.TYPE_ROCK,
    Type.TYPE_ROCK ],
    [ "SPECIES_POLITOED",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_HOPPIP",
    Type.TYPE_GRASS,
    Type.TYPE_FLYING ],
    [ "SPECIES_SKIPLOOM",
    Type.TYPE_GRASS,
    Type.TYPE_FLYING ],
    [ "SPECIES_JUMPLUFF",
    Type.TYPE_GRASS,
    Type.TYPE_FLYING ],
    [ "SPECIES_AIPOM",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_SUNKERN",
    Type.TYPE_GRASS,
    Type.TYPE_GRASS ],
    [ "SPECIES_SUNFLORA",
    Type.TYPE_GRASS,
    Type.TYPE_GRASS ],
    [ "SPECIES_YANMA",
    Type.TYPE_BUG,
    Type.TYPE_FLYING ],
    [ "SPECIES_WOOPER",
    Type.TYPE_WATER,
    Type.TYPE_GROUND ],
    [ "SPECIES_QUAGSIRE",
    Type.TYPE_WATER,
    Type.TYPE_GROUND ],
    [ "SPECIES_ESPEON",
    Type.TYPE_PSYCHIC,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_UMBREON",
    Type.TYPE_DARK,
    Type.TYPE_DARK ],
    [ "SPECIES_MURKROW",
    Type.TYPE_DARK,
    Type.TYPE_FLYING ],
    [ "SPECIES_SLOWKING",
    Type.TYPE_WATER,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_MISDREAVUS",
    Type.TYPE_GHOST,
    Type.TYPE_GHOST ],
    [ "SPECIES_UNOWN",
    Type.TYPE_PSYCHIC,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_WOBBUFFET",
    Type.TYPE_PSYCHIC,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_GIRAFARIG",
    Type.TYPE_NORMAL,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_PINECO",
    Type.TYPE_BUG,
    Type.TYPE_BUG ],
    [ "SPECIES_FORRETRESS",
    Type.TYPE_BUG,
    Type.TYPE_STEEL ],
    [ "SPECIES_DUNSPARCE",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_GLIGAR",
    Type.TYPE_GROUND,
    Type.TYPE_FLYING ],
    [ "SPECIES_STEELIX",
    Type.TYPE_STEEL,
    Type.TYPE_GROUND ],
    [ "SPECIES_SNUBBULL",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_GRANBULL",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_QWILFISH",
    Type.TYPE_WATER,
    Type.TYPE_POISON ],
    [ "SPECIES_SCIZOR",
    Type.TYPE_BUG,
    Type.TYPE_STEEL ],
    [ "SPECIES_SHUCKLE",
    Type.TYPE_BUG,
    Type.TYPE_ROCK ],
    [ "SPECIES_HERACROSS",
    Type.TYPE_BUG,
    Type.TYPE_FIGHTING ],
    [ "SPECIES_SNEASEL",
    Type.TYPE_DARK,
    Type.TYPE_ICE ],
    [ "SPECIES_TEDDIURSA",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_URSARING",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_SLUGMA",
    Type.TYPE_FIRE,
    Type.TYPE_FIRE ],
    [ "SPECIES_MAGCARGO",
    Type.TYPE_FIRE,
    Type.TYPE_ROCK ],
    [ "SPECIES_SWINUB",
    Type.TYPE_ICE,
    Type.TYPE_GROUND ],
    [ "SPECIES_PILOSWINE",
    Type.TYPE_ICE,
    Type.TYPE_GROUND ],
    [ "SPECIES_CORSOLA",
    Type.TYPE_WATER,
    Type.TYPE_ROCK ],
    [ "SPECIES_REMORAID",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_OCTILLERY",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_DELIBIRD",
    Type.TYPE_ICE,
    Type.TYPE_FLYING ],
    [ "SPECIES_MANTINE",
    Type.TYPE_WATER,
    Type.TYPE_FLYING ],
    [ "SPECIES_SKARMORY",
    Type.TYPE_STEEL,
    Type.TYPE_FLYING ],
    [ "SPECIES_HOUNDOUR",
    Type.TYPE_DARK,
    Type.TYPE_FIRE ],
    [ "SPECIES_HOUNDOOM",
    Type.TYPE_DARK,
    Type.TYPE_FIRE ],
    [ "SPECIES_KINGDRA",
    Type.TYPE_WATER,
    Type.TYPE_DRAGON ],
    [ "SPECIES_PHANPY",
    Type.TYPE_GROUND,
    Type.TYPE_GROUND ],
    [ "SPECIES_DONPHAN",
    Type.TYPE_GROUND,
    Type.TYPE_GROUND ],
    [ "SPECIES_PORYGON2",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_STANTLER",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_SMEARGLE",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_TYROGUE",
    Type.TYPE_FIGHTING,
    Type.TYPE_FIGHTING ],
    [ "SPECIES_HITMONTOP",
    Type.TYPE_FIGHTING,
    Type.TYPE_FIGHTING ],
    [ "SPECIES_SMOOCHUM",
    Type.TYPE_ICE,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_ELEKID",
    Type.TYPE_ELECTRIC,
    Type.TYPE_ELECTRIC ],
    [ "SPECIES_MAGBY",
    Type.TYPE_FIRE,
    Type.TYPE_FIRE ],
    [ "SPECIES_MILTANK",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_BLISSEY",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_RAIKOU",
    Type.TYPE_ELECTRIC,
    Type.TYPE_ELECTRIC ],
    [ "SPECIES_ENTEI",
    Type.TYPE_FIRE,
    Type.TYPE_FIRE ],
    [ "SPECIES_SUICUNE",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_LARVITAR",
    Type.TYPE_ROCK,
    Type.TYPE_GROUND ],
    [ "SPECIES_PUPITAR",
    Type.TYPE_ROCK,
    Type.TYPE_GROUND ],
    [ "SPECIES_TYRANITAR",
    Type.TYPE_ROCK,
    Type.TYPE_DARK ],
    [ "SPECIES_LUGIA",
    Type.TYPE_PSYCHIC,
    Type.TYPE_FLYING ],
    [ "SPECIES_HO_OH",
    Type.TYPE_FIRE,
    Type.TYPE_FLYING ],
    [ "SPECIES_CELEBI",
    Type.TYPE_PSYCHIC,
    Type.TYPE_GRASS ],
    [ "SPECIES_OLD_UNOWN_B",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_C",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_D",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_E",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_F",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_G",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_H",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_I",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_J",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_K",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_L",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_M",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_N",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_O",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_P",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_Q",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_R",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_S",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_T",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_U",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_V",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_W",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_X",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_Y",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_OLD_UNOWN_Z",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_TREECKO",
    Type.TYPE_GRASS,
    Type.TYPE_GRASS ],
    [ "SPECIES_GROVYLE",
    Type.TYPE_GRASS,
    Type.TYPE_GRASS ],
    [ "SPECIES_SCEPTILE",
    Type.TYPE_GRASS,
    Type.TYPE_GRASS ],
    [ "SPECIES_TORCHIC",
    Type.TYPE_FIRE,
    Type.TYPE_FIRE ],
    [ "SPECIES_COMBUSKEN",
    Type.TYPE_FIRE,
    Type.TYPE_FIGHTING ],
    [ "SPECIES_BLAZIKEN",
    Type.TYPE_FIRE,
    Type.TYPE_FIGHTING ],
    [ "SPECIES_MUDKIP",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_MARSHTOMP",
    Type.TYPE_WATER,
    Type.TYPE_GROUND ],
    [ "SPECIES_SWAMPERT",
    Type.TYPE_WATER,
    Type.TYPE_GROUND ],
    [ "SPECIES_POOCHYENA",
    Type.TYPE_DARK,
    Type.TYPE_DARK ],
    [ "SPECIES_MIGHTYENA",
    Type.TYPE_DARK,
    Type.TYPE_DARK ],
    [ "SPECIES_ZIGZAGOON",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_LINOONE",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_WURMPLE",
    Type.TYPE_BUG,
    Type.TYPE_BUG ],
    [ "SPECIES_SILCOON",
    Type.TYPE_BUG,
    Type.TYPE_BUG ],
    [ "SPECIES_BEAUTIFLY",
    Type.TYPE_BUG,
    Type.TYPE_FLYING ],
    [ "SPECIES_CASCOON",
    Type.TYPE_BUG,
    Type.TYPE_BUG ],
    [ "SPECIES_DUSTOX",
    Type.TYPE_BUG,
    Type.TYPE_POISON ],
    [ "SPECIES_LOTAD",
    Type.TYPE_WATER,
    Type.TYPE_GRASS ],
    [ "SPECIES_LOMBRE",
    Type.TYPE_WATER,
    Type.TYPE_GRASS ],
    [ "SPECIES_LUDICOLO",
    Type.TYPE_WATER,
    Type.TYPE_GRASS ],
    [ "SPECIES_SEEDOT",
    Type.TYPE_GRASS,
    Type.TYPE_GRASS ],
    [ "SPECIES_NUZLEAF",
    Type.TYPE_GRASS,
    Type.TYPE_DARK ],
    [ "SPECIES_SHIFTRY",
    Type.TYPE_GRASS,
    Type.TYPE_DARK ],
    [ "SPECIES_NINCADA",
    Type.TYPE_BUG,
    Type.TYPE_GROUND ],
    [ "SPECIES_NINJASK",
    Type.TYPE_BUG,
    Type.TYPE_FLYING ],
    [ "SPECIES_SHEDINJA",
    Type.TYPE_BUG,
    Type.TYPE_GHOST ],
    [ "SPECIES_TAILLOW",
    Type.TYPE_NORMAL,
    Type.TYPE_FLYING ],
    [ "SPECIES_SWELLOW",
    Type.TYPE_NORMAL,
    Type.TYPE_FLYING ],
    [ "SPECIES_SHROOMISH",
    Type.TYPE_GRASS,
    Type.TYPE_GRASS ],
    [ "SPECIES_BRELOOM",
    Type.TYPE_GRASS,
    Type.TYPE_FIGHTING ],
    [ "SPECIES_SPINDA",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_WINGULL",
    Type.TYPE_WATER,
    Type.TYPE_FLYING ],
    [ "SPECIES_PELIPPER",
    Type.TYPE_WATER,
    Type.TYPE_FLYING ],
    [ "SPECIES_SURSKIT",
    Type.TYPE_BUG,
    Type.TYPE_WATER ],
    [ "SPECIES_MASQUERAIN",
    Type.TYPE_BUG,
    Type.TYPE_FLYING ],
    [ "SPECIES_WAILMER",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_WAILORD",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_SKITTY",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_DELCATTY",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_KECLEON",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_BALTOY",
    Type.TYPE_GROUND,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_CLAYDOL",
    Type.TYPE_GROUND,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_NOSEPASS",
    Type.TYPE_ROCK,
    Type.TYPE_ROCK ],
    [ "SPECIES_TORKOAL",
    Type.TYPE_FIRE,
    Type.TYPE_FIRE ],
    [ "SPECIES_SABLEYE",
    Type.TYPE_DARK,
    Type.TYPE_GHOST ],
    [ "SPECIES_BARBOACH",
    Type.TYPE_WATER,
    Type.TYPE_GROUND ],
    [ "SPECIES_WHISCASH",
    Type.TYPE_WATER,
    Type.TYPE_GROUND ],
    [ "SPECIES_LUVDISC",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_CORPHISH",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_CRAWDAUNT",
    Type.TYPE_WATER,
    Type.TYPE_DARK ],
    [ "SPECIES_FEEBAS",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_MILOTIC",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_CARVANHA",
    Type.TYPE_WATER,
    Type.TYPE_DARK ],
    [ "SPECIES_SHARPEDO",
    Type.TYPE_WATER,
    Type.TYPE_DARK ],
    [ "SPECIES_TRAPINCH",
    Type.TYPE_GROUND,
    Type.TYPE_GROUND ],
    [ "SPECIES_VIBRAVA",
    Type.TYPE_GROUND,
    Type.TYPE_DRAGON ],
    [ "SPECIES_FLYGON",
    Type.TYPE_GROUND,
    Type.TYPE_DRAGON ],
    [ "SPECIES_MAKUHITA",
    Type.TYPE_FIGHTING,
    Type.TYPE_FIGHTING ],
    [ "SPECIES_HARIYAMA",
    Type.TYPE_FIGHTING,
    Type.TYPE_FIGHTING ],
    [ "SPECIES_ELECTRIKE",
    Type.TYPE_ELECTRIC,
    Type.TYPE_ELECTRIC ],
    [ "SPECIES_MANECTRIC",
    Type.TYPE_ELECTRIC,
    Type.TYPE_ELECTRIC ],
    [ "SPECIES_NUMEL",
    Type.TYPE_FIRE,
    Type.TYPE_GROUND ],
    [ "SPECIES_CAMERUPT",
    Type.TYPE_FIRE,
    Type.TYPE_GROUND ],
    [ "SPECIES_SPHEAL",
    Type.TYPE_ICE,
    Type.TYPE_WATER ],
    [ "SPECIES_SEALEO",
    Type.TYPE_ICE,
    Type.TYPE_WATER ],
    [ "SPECIES_WALREIN",
    Type.TYPE_ICE,
    Type.TYPE_WATER ],
    [ "SPECIES_CACNEA",
    Type.TYPE_GRASS,
    Type.TYPE_GRASS ],
    [ "SPECIES_CACTURNE",
    Type.TYPE_GRASS,
    Type.TYPE_DARK ],
    [ "SPECIES_SNORUNT",
    Type.TYPE_ICE,
    Type.TYPE_ICE ],
    [ "SPECIES_GLALIE",
    Type.TYPE_ICE,
    Type.TYPE_ICE ],
    [ "SPECIES_LUNATONE",
    Type.TYPE_ROCK,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_SOLROCK",
    Type.TYPE_ROCK,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_AZURILL",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_SPOINK",
    Type.TYPE_PSYCHIC,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_GRUMPIG",
    Type.TYPE_PSYCHIC,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_PLUSLE",
    Type.TYPE_ELECTRIC,
    Type.TYPE_ELECTRIC ],
    [ "SPECIES_MINUN",
    Type.TYPE_ELECTRIC,
    Type.TYPE_ELECTRIC ],
    [ "SPECIES_MAWILE",
    Type.TYPE_STEEL,
    Type.TYPE_STEEL ],
    [ "SPECIES_MEDITITE",
    Type.TYPE_FIGHTING,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_MEDICHAM",
    Type.TYPE_FIGHTING,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_SWABLU",
    Type.TYPE_NORMAL,
    Type.TYPE_FLYING ],
    [ "SPECIES_ALTARIA",
    Type.TYPE_DRAGON,
    Type.TYPE_FLYING ],
    [ "SPECIES_WYNAUT",
    Type.TYPE_PSYCHIC,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_DUSKULL",
    Type.TYPE_GHOST,
    Type.TYPE_GHOST ],
    [ "SPECIES_DUSCLOPS",
    Type.TYPE_GHOST,
    Type.TYPE_GHOST ],
    [ "SPECIES_ROSELIA",
    Type.TYPE_GRASS,
    Type.TYPE_POISON ],
    [ "SPECIES_SLAKOTH",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_VIGOROTH",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_SLAKING",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_GULPIN",
    Type.TYPE_POISON,
    Type.TYPE_POISON ],
    [ "SPECIES_SWALOT",
    Type.TYPE_POISON,
    Type.TYPE_POISON ],
    [ "SPECIES_TROPIUS",
    Type.TYPE_GRASS,
    Type.TYPE_FLYING ],
    [ "SPECIES_WHISMUR",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_LOUDRED",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_EXPLOUD",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_CLAMPERL",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_HUNTAIL",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_GOREBYSS",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_ABSOL",
    Type.TYPE_DARK,
    Type.TYPE_DARK ],
    [ "SPECIES_SHUPPET",
    Type.TYPE_GHOST,
    Type.TYPE_GHOST ],
    [ "SPECIES_BANETTE",
    Type.TYPE_GHOST,
    Type.TYPE_GHOST ],
    [ "SPECIES_SEVIPER",
    Type.TYPE_POISON,
    Type.TYPE_POISON ],
    [ "SPECIES_ZANGOOSE",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_RELICANTH",
    Type.TYPE_WATER,
    Type.TYPE_ROCK ],
    [ "SPECIES_ARON",
    Type.TYPE_STEEL,
    Type.TYPE_ROCK ],
    [ "SPECIES_LAIRON",
    Type.TYPE_STEEL,
    Type.TYPE_ROCK ],
    [ "SPECIES_AGGRON",
    Type.TYPE_STEEL,
    Type.TYPE_ROCK ],
    [ "SPECIES_CASTFORM",
    Type.TYPE_NORMAL,
    Type.TYPE_NORMAL ],
    [ "SPECIES_VOLBEAT",
    Type.TYPE_BUG,
    Type.TYPE_BUG ],
    [ "SPECIES_ILLUMISE",
    Type.TYPE_BUG,
    Type.TYPE_BUG ],
    [ "SPECIES_LILEEP",
    Type.TYPE_ROCK,
    Type.TYPE_GRASS ],
    [ "SPECIES_CRADILY",
    Type.TYPE_ROCK,
    Type.TYPE_GRASS ],
    [ "SPECIES_ANORITH",
    Type.TYPE_ROCK,
    Type.TYPE_BUG ],
    [ "SPECIES_ARMALDO",
    Type.TYPE_ROCK,
    Type.TYPE_BUG ],
    [ "SPECIES_RALTS",
    Type.TYPE_PSYCHIC,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_KIRLIA",
    Type.TYPE_PSYCHIC,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_GARDEVOIR",
    Type.TYPE_PSYCHIC,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_BAGON",
    Type.TYPE_DRAGON,
    Type.TYPE_DRAGON ],
    [ "SPECIES_SHELGON",
    Type.TYPE_DRAGON,
    Type.TYPE_DRAGON ],
    [ "SPECIES_SALAMENCE",
    Type.TYPE_DRAGON,
    Type.TYPE_FLYING ],
    [ "SPECIES_BELDUM",
    Type.TYPE_STEEL,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_METANG",
    Type.TYPE_STEEL,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_METAGROSS",
    Type.TYPE_STEEL,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_REGIROCK",
    Type.TYPE_ROCK,
    Type.TYPE_ROCK ],
    [ "SPECIES_REGICE",
    Type.TYPE_ICE,
    Type.TYPE_ICE ],
    [ "SPECIES_REGISTEEL",
    Type.TYPE_STEEL,
    Type.TYPE_STEEL ],
    [ "SPECIES_KYOGRE",
    Type.TYPE_WATER,
    Type.TYPE_WATER ],
    [ "SPECIES_GROUDON",
    Type.TYPE_GROUND,
    Type.TYPE_GROUND ],
    [ "SPECIES_RAYQUAZA",
    Type.TYPE_DRAGON,
    Type.TYPE_FLYING ],
    [ "SPECIES_LATIAS",
    Type.TYPE_DRAGON,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_LATIOS",
    Type.TYPE_DRAGON,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_JIRACHI",
    Type.TYPE_STEEL,
    Type.TYPE_PSYCHIC ],
    [ "SPECIES_DEOXYS",
    Type.TYPE_PSYCHIC,
    Type.TYPE_PSYCHIC ]]

def getRandomPokemon():
    """Returns a random pokemon."""
    return ALL_POKE[random.randint(0, len(ALL_POKE) - 1)][0]

def getRandomPokemonOf(type):
    """Return a random pokemon of given type."""
    poke_type = [poke for poke in ALL_POKE if poke[1] == type or poke[2] == type]
    return poke_type[random.randint(0, len(poke_type) - 1)][0]