Level_6_MapScripts::
	.byte 0

Level_6_Trainer_1::
	trainerbattle_single TRAINER_L6_1, SeafloorCavern_Room4_Text_234CCA, SeafloorCavern_Room4_Text_234CF3
	msgbox SeafloorCavern_Room4_Text_234CFC, MSGBOX_AUTOCLOSE
	end

Level_6_Trainer_2::
	trainerbattle_single TRAINER_L6_2, SeafloorCavern_Room4_Text_234D3A, SeafloorCavern_Room4_Text_234D68
	msgbox SeafloorCavern_Room4_Text_234D79, MSGBOX_AUTOCLOSE
	end

Level_6_Trainer_3::
	trainerbattle_single TRAINER_L6_3, SeafloorCavern_Room1_Text_23481A, SeafloorCavern_Room1_Text_23484A
	msgbox SeafloorCavern_Room1_Text_23485D, MSGBOX_AUTOCLOSE
	end