NewMap1_EventObjects::
	object_event 1, EVENT_OBJ_GFX_MART_EMPLOYEE, 0, 1, 3, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, FALSE, 0, NewMap1_MartScript, 0
	object_event 2, EVENT_OBJ_GFX_BEAUTY, 0, 4, 3, 3, MOVEMENT_TYPE_WANDER_AROUND, 0, 0, FALSE, 0, NewMap1_Beauty, 0
	object_event 3, EVENT_OBJ_GFX_BIRCHS_BAG, 0, 9, 3, 3, MOVEMENT_TYPE_NONE, 0, 0, FALSE, 0, NewMap1_Bag, 0

NewMap1_MapEvents::
	map_events NewMap1_EventObjects, 0x0, 0x0, 0x0
