Level_4_MapScripts::
	.byte 0

Level_4_Trainer_1::
	trainerbattle_single TRAINER_L4_1, Route123_Text_29FBEB, Route123_Text_29FC23
	msgbox Route123_Text_29FC42, MSGBOX_AUTOCLOSE
	end

Level_4_Trainer_2::
	trainerbattle_single TRAINER_L4_2, Route123_Text_29FC6F, Route123_Text_29FCD6
	msgbox Route123_Text_29FCF4, MSGBOX_AUTOCLOSE
	end

Level_4_Trainer_3::
	trainerbattle_single TRAINER_L4_3, Route123_Text_29FD1D, Route123_Text_29FD53
	msgbox Route123_Text_29FD7B, MSGBOX_AUTOCLOSE
	end

Level_4_Trainer_4::
	trainerbattle_single TRAINER_L4_4, Route123_Text_29FDBA, Route123_Text_29FE1E
	msgbox Route123_Text_29FE2A, MSGBOX_AUTOCLOSE
	end
