Lobby_EventObjects::
	object_event 1, EVENT_OBJ_GFX_MART_EMPLOYEE, 0, 1, 3, 3, MOVEMENT_TYPE_FACE_RIGHT, 0, 0, FALSE, 0, Lobby_MartScript, 0
	object_event 2, EVENT_OBJ_GFX_BEAUTY, 0, 7, 5, 3, MOVEMENT_TYPE_FACE_DOWN_AND_UP, 0, 0, FALSE, 0, Lobby_Beauty, 0
	object_event 3, EVENT_OBJ_GFX_BIRCHS_BAG, 0, 10, 4, 3, MOVEMENT_TYPE_NONE, 0, 0, FALSE, 0, Lobby_Bag, FLAG_LOBBY_STARTER
	object_event 4, EVENT_OBJ_GFX_KIRLIA, 0, 1, 6, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, FALSE, 0, Lobby_PreWarp, 0

Lobby_MapEvents::
	map_events Lobby_EventObjects, 0x0, 0x0, 0x0
