Level_8_EventObjects::
	object_event 1, EVENT_OBJ_GFX_ITEM_BALL, 0, 12, 18, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, FALSE, 0, Level_8_Ball_1, FLAG_0x4B5
	object_event 2, EVENT_OBJ_GFX_ITEM_BALL, 0, 8, 14, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, FALSE, 0, Level_8_Ball_2, FLAG_0x4B6
	object_event 3, EVENT_OBJ_GFX_KIRLIA, 0, 5, 14, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, FALSE, 0, Level_8_Warp, 0
	object_event 4, EVENT_OBJ_GFX_TUBER_F, 0, 10, 11, 3, MOVEMENT_TYPE_WANDER_UP_AND_DOWN, 0, 7, TRUE, 7, Level_8_Trainer_1, FLAG_0x4B7

Level_8_MapEvents::
	map_events Level_8_EventObjects, 0x0, 0x0, 0x0
