Level_1_EventObjects::
	object_event 1, EVENT_OBJ_GFX_MAY_NORMAL, 0, 15, 7, 3, MOVEMENT_TYPE_TREE_DISGUISE, 0, 0, TRUE, 3, Level_1_Trainer_1, FLAG_L1_TRAINER_1
	object_event 2, EVENT_OBJ_GFX_ITEM_BALL, 0, 4, 5, 3, MOVEMENT_TYPE_NONE, 0, 0, FALSE, 0, Level_1_Ball_1, FLAG_L1_BALL_1
	object_event 3, EVENT_OBJ_GFX_ITEM_BALL, 0, 14, 17, 3, MOVEMENT_TYPE_NONE, 0, 0, FALSE, 0, Level_1_Ball_2, FLAG_L1_BALL_2
	object_event 4, EVENT_OBJ_GFX_KIRLIA, 0, 9, 6, 3, MOVEMENT_TYPE_LOOK_AROUND, 0, 0, FALSE, 0, Level_1_Warp, 0

Level_1_MapEvents::
	map_events Level_1_EventObjects, 0x0, 0x0, 0x0
