Level_3_MapScripts::
	.byte 0

Level_3_Trainer_1::
	trainerbattle_single TRAINER_L3_1, Route121_Text_29FA1E, Route121_Text_29FA64
	msgbox Route121_Text_29FA73, MSGBOX_AUTOCLOSE
	end

Level_3_Trainer_2::
	trainerbattle_single TRAINER_L3_2, Route121_Text_29FB35, Route121_Text_29FB8C
	msgbox Route121_Text_29FBA8, MSGBOX_AUTOCLOSE
	end

Level_3_Trainer_3::
	trainerbattle_single TRAINER_L3_3, Route121_Text_29F6E4, Route121_Text_29F710
	msgbox Route121_Text_29F740, MSGBOX_AUTOCLOSE
	end
	